version: "3.2"
services:
  server:
    container_name: node-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - notification
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - notification
  db: 
    image: postgres
    restart: always
    ports:
      - 5433:5432
    depends_on:
      - rabbitmq
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - notification
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  notification:
    driver: bridge
volumes:
  pgdata: